apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:4.0.8
          name: mongo
          args: ["--config", "/etc/mongod.conf"]
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-mongo.js
              subPath: init-mongo.js
            - name: config-volume
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: init-script
          configMap:
            name: mongo-config
            items:
              - key: init-mongo.js
                path: init-mongo.js
        - name: config-volume
          configMap:
            name: mongo-config
            items:
              - key: mongod.conf
                path: mongod.conf
